### ISSUE TITLE
Traefik has a error entryPoint "web-secure" doesn't exist

### ISSUE THREAD

**Issue by canghai908** [iFargle/headscale-webui#11]
I use trafik but cann't work ok
![image](https://user-images.githubusercontent.com/1450994/218262929-dff913ae-5d0f-4371-bc4c-bf8039913b07.png)
my docker-compose file is 
```
version: "3"
services:
  headscale-webui:
    image: ghcr.io/ifargle/headscale-webui:latest
    container_name: headscale-webui
    ports:
      - "5000:5000"
    environment:
      - TZ=UTC                                 # Timezone
      - HS_SERVER=http://222.110.122.115:8080                 # Set this to your Headscale server's URL.  It will need to access /api/ on Headscale.
      - BASE_PATH="/admin"                     # Default, can be anything you want.  Tailscale's Windows app expects "HS_SERVER/admin"
      - KEY="4E3jPM9UUw0tvriFjBAKUfwM9yhh7D8GcttnfFR1KlM="             # Generate with "openssl rand -base64 32"
    volumes:
      - ./volume:/data                         # Headscale-WebUI's storage
      - ./headscale/config/:/etc/headscale/:ro # Headscale's config storage location.  Used to read your Headscale config.
    labels:
      # Traefik Configs
      - "traefik.enable=true"
      - "traefik.http.routers.headscale-webui.entrypoints=web-secure"
      - "traefik.http.routers.headscale-webui.rule=Host(`headscale.opst.net`) && (PathPrefix(`/admin/`) || PathPrefix(`/admin`))"
      - "traefik.http.services.headscale-webui.loadbalancer.server.port=5000"
      - "traefik.http.routers.headscale-webui.tls.certresolver=letsencrypt"
        # redirect /admin to /
      - "traefik.http.middlewares.headscale-webui-stripprefix.stripprefix.forceslash=true"
      - "traefik.http.middlewares.headscale-webui-stripprefix.stripprefix.prefixes=/admin/
```
I use http://headscale.opst.net  is 404
