### ISSUE TITLE
Unable to validate the API key

### ISSUE THREAD

**Issue by henry-bao** [iFargle/headscale-webui#20]
I followed the instructions shown on the website, yet it displays the following when I enter the API key that I just generated from my control server
```
Error
Key authentication failed. Check your key.
``` 

this is my docker-compose file (sorry for the multiple issues, thanks a bunch!)
```yaml
version: "3"
services:
  headscale-webui:
    image: ghcr.io/ifargle/headscale-webui:latest
    container_name: headscale-webui
    ports:
      - 5000:5000
    environment:
      - TZ=PST
      - HS_SERVER=http://10.1.0.2:27896
      - BASE_PATH="/admin"
      - KEY="some-base64-key"
    volumes:
      - /root/docker/headscale-webui:/data
      - /root/docker/headscale/config/:/etc/headscale/:ro
    restart: unless-stopped
  ```
