### ISSUE TITLE
Error - /data not writable

### ISSUE THREAD

**Issue by threerog** [iFargle/headscale-webui#72]
```
Error - /data not writable
/data is not writable. Please ensure your permissions are correct. /data mount should be writable by UID/GID 1000:1000.
```

```
version: "3"
services:
  headscale-webui:
    image: ghcr.io/ifargle/headscale-webui:latest
    container_name: headscale-webui
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
      - COLOR=red 
      - HS_SERVER=http://0.0.0.0:8080
      - DOMAIN_NAME=http://0.0.0.0:5000 
      - SCRIPT_NAME=/admin
      - KEY="PSDSzZAXi0UTtod8oQEO/13u8EK0oR+PjB+h2+XUtWI="
      - AUTH_TYPE=basic
      - LOG_LEVEL=info
      - BASIC_AUTH_USER=admin
      - BASIC_AUTH_PASS=admin
    volumes:
      - /etc/headscale/ui:/data:rw
      - /etc/headscale/config:/etc/headscale:ro
```
