### ISSUE TITLE
[bug] 0.7.1 can't reach HS_SERVER, but 0.6.1 can

### ISSUE THREAD

**Issue by 1itt1eB0y** [iFargle/headscale-webui#94]
```yaml
  headscale-webui:
    image: ifargle/headscale-webui:v0.6.1
    container_name: headscale-webui
    network_mode: bridge
    ports:
      - 10.10.0.1:5000:5000
    environment:
      - TZ=Asia/Shanghai
      - COLOR=red                              # Use the base colors (ie, no darken-3, etc) -
      - HS_SERVER=https://mydomain.com:8080/    # Reachable endpoint for your Headscale serv
      - DOMAIN_NAME=http://myip:5000  # The base domain name for this container.
      - SCRIPT_NAME=/admin                     # This is your applications base path (wsgi requires the name "SCRIPT_NAME").  Remove if you are hosing at the root /
      - KEY="mykey"             # Generate with "openssl rand -base64 32" - used to encrypt your key on disk.
      - LOG_LEVEL=debug                         # Log level.  "DEBUG", "ERROR", "WARNING", or "INFO".  Default "INFO"

    volumes:
      - ./webui-data:/data                         # Headscale-WebUI's storage.  Make sure ./volume is readable by UID 1000 (chown 1000:1000 ./volume)
      - ./config/:/etc/headscale/:ro # Headscale's config storage location.  Used to read your Headscale config.
```

0.7.1 will throw an error:
```Headscale server API is unreachable```
![图片](https://user-images.githubusercontent.com/29831189/234738909-7cc63130-d718-49c6-ba4f-118479e54fe1.png)

with same configuration, 0.6.1 can run properly
![图片](https://user-images.githubusercontent.com/29831189/234738839-59e478b2-ffe6-42f6-b6a0-969312525fe8.png)
